WARM_BOX = ENV["VM_WARM_BOX"]
USERNAME = ENV["VM_USERNAME"]
VM_MEMORY = ENV["VM_MEMORY"] || "4096"
VM_CPUS = ENV["VM_CPUS"] || "4"
VM_DISK_SIZE = ENV["VM_DISK_SIZE"] || "60GB"

Vagrant.configure("2") do |config|
    config.vm.box = WARM_BOX
    config.disksize.size = VM_DISK_SIZE

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = VM_MEMORY
        vb.cpus = VM_CPUS
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        vb.customize ["modifyvm", :id, "--audio", "none"]
    end

    config.vm.provision "shell", privileged: false, inline: <<-SHELL
        echo 'Creating ubuntu-config-scripts directory'
        sudo mkdir -p '/home/#{USERNAME}/ubuntu-config-scripts'

        echo 'Setting ownership for ubuntu-config-scripts'
        sudo chown -R #{USERNAME} '/home/#{USERNAME}/ubuntu-config-scripts'
    SHELL

    config.vm.provision "file", source: "../bin", destination: "/home/#{USERNAME}/ubuntu-config-scripts/bin"
    config.vm.provision "file", source: "../run.sh", destination: "/home/#{USERNAME}/ubuntu-config-scripts/run.sh"
    config.vm.provision "file", source: "../run_in_vagrant.sh", destination: "/home/#{USERNAME}/ubuntu-config-scripts/run_in_vagrant.sh"

    config.vm.provision "shell", privileged: false, inline: <<-SHELL
        set -e

        echo 'Setting idle-delay to 0'
        gsettings set org.gnome.desktop.session idle-delay 0

        echo 'Setting permissions for ubuntu-config-scripts'
        sudo chmod +x -R '/home/#{USERNAME}/ubuntu-config-scripts'

        echo 'Creating UbuntuConfigScripts test service'
        mkdir '/home/#{USERNAME}/.config/autostart'
        echo '[Desktop Entry]'                                                                          | tee    '/home/#{USERNAME}/.config/autostart/UbuntuConfigScripts.desktop' > /dev/null
        echo 'Name=UbuntuConfigScripts'                                                                 | tee -a '/home/#{USERNAME}/.config/autostart/UbuntuConfigScripts.desktop' > /dev/null
        echo 'Exec=gnome-terminal -- bash -e /home/#{USERNAME}/ubuntu-config-scripts/run_in_vagrant.sh' | tee -a '/home/#{USERNAME}/.config/autostart/UbuntuConfigScripts.desktop' > /dev/null
        echo 'Type=Application'                                                                         | tee -a '/home/#{USERNAME}/.config/autostart/UbuntuConfigScripts.desktop' > /dev/null
        echo ''                                                                                         | tee -a '/home/#{USERNAME}/.config/autostart/UbuntuConfigScripts.desktop' > /dev/null
    SHELL
end
